server.port=8090
spring.application.name=apiusuariosdas

#Conexion a base de datos
spring.datasource.url=jdbc:postgresql://usuariosdsadb.postgres.database.azure.com:5432/usuariosdsadb
spring.datasource.username=pgdsaadmin
spring.datasource.password=dsa_admin$@2025
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true